/**
 * Process Flow Constants
 * Business defaults for process flow metrics
 */
export const PROCESS_FLOW = {
  MAX_QUEUE_SIZE: 50,
  QUEUE_HEALTH_THRESHOLD: 80,
  QUEUE_HEALTH_MEDIUM: 50,
  DEFAULT_CYCLE_TIME: 4.2,
  DEFAULT_QUEUE_CAPACITY: 100,
  DEFAULT_RESOURCE_TOTAL: 15,
  DEFAULT_RESOURCE_USED: 12,
  DEFAULT_RESOURCE_NAME: "analyst",
  TIME_UNIT: "days",
  SLA_CATEGORIES: {
    RISK_REVIEW: "Risk Review",
    MANUAL_REVIEW: "Manual Review",
  },
  CURRENCY: "USD",
  API_UPTIME: "140ms",
  DEFAULT_BEST_CASE_CYCLE_TIME: 2.1,
  DEFAULT_WORST_CASE_CYCLE_TIME: 8.7,
  DEFAULT_LABOR_COST: 89,
  DEFAULT_LABOR_PERCENTAGE: 63,
  DEFAULT_SYSTEMS_COST: 53,
  DEFAULT_SYSTEMS_PERCENTAGE: 37,
  DEFAULT_TARGET_VARIANCE: 3,
  DEFAULT_RISK_REVIEW_COUNT: 8,
  DEFAULT_MANUAL_REVIEW_COUNT: 4,
  DEFAULT_QUEUE_HEALTH: 73,
  DEFAULT_ERROR_RATE: 0.62,
  DEFAULT_AVG_BREACH_DURATION: 2.3,
} as const;
