[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:store]
command=node /app/store/apps/store/server.js
directory=/app/store
user=nextjs
autostart=true
autorestart=true
environment=PORT="5001",HOSTNAME="0.0.0.0"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:landing]
command=node /app/landing/apps/landing/server.js
directory=/app/landing
user=nextjs
autostart=true
autorestart=true
environment=PORT="5004",HOSTNAME="0.0.0.0"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:payments]
command=node /app/payments/apps/payments/server.js
directory=/app/payments
user=nextjs
autostart=true
autorestart=true
environment=PORT="5005",HOSTNAME="0.0.0.0"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:admin]
command=node /app/admin/apps/admin/server.js
directory=/app/admin
user=nextjs
autostart=true
autorestart=true
environment=PORT="5002",HOSTNAME="0.0.0.0"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:auth]
command=node /app/auth/apps/auth/server.js
directory=/app/auth
user=nextjs
autostart=true
autorestart=true
environment=PORT="5000",HOSTNAME="0.0.0.0",AUTH_COOKIES_SECURE="true"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:playground]
command=node /app/playground/apps/playground/server.js
directory=/app/playground
user=nextjs
autostart=true
autorestart=true
environment=PORT="5003",HOSTNAME="0.0.0.0"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
