import type { PermissionGroup } from "./types";

export const PERMISSION_GROUPS: PermissionGroup[] = [
  {
    key: "products",
    labelKey: "productsCommerce",
    permissions: [
      "products.create",
      "products.read",
      "products.update",
      "products.delete",
      "product_images.create",
      "product_images.read",
      "product_images.delete",
      "product_reviews.create",
      "product_reviews.read",
      "product_reviews.update",
      "product_reviews.delete",
    ],
  },
  {
    key: "orders",
    labelKey: "ordersPayments",
    permissions: [
      "orders.create",
      "orders.read",
      "orders.update",
      "receipts.create",
      "receipts.read",
      "receipts.delete",
    ],
  },
  {
    key: "seller",
    labelKey: "sellerConfig",
    permissions: [
      "seller_payment_methods.create",
      "seller_payment_methods.read",
      "seller_payment_methods.update",
      "seller_payment_methods.delete",
    ],
  },
  {
    key: "admin_platform",
    labelKey: "adminPlatform",
    permissions: [
      "payment_method_types.create",
      "payment_method_types.read",
      "payment_method_types.update",
      "payment_method_types.delete",
      "payment_settings.read",
      "payment_settings.update",
      "templates.create",
      "templates.read",
      "templates.update",
      "templates.delete",
    ],
  },
  {
    key: "admin_users",
    labelKey: "adminUsersAudit",
    permissions: [
      "audit.read",
      "user_permissions.create",
      "user_permissions.read",
      "user_permissions.update",
      "user_permissions.delete",
    ],
  },
  {
    key: "events",
    labelKey: "eventsCheckins",
    permissions: [
      "events.create",
      "events.read",
      "events.update",
      "events.delete",
      "check_ins.create",
      "check_ins.read",
      "check_ins.update",
    ],
  },
];

export const PERMISSION_TEMPLATES: Record<string, string[]> = {
  buyer: [
    "products.read",
    "orders.create",
    "orders.read",
    "receipts.create",
    "receipts.read",
    "product_reviews.create",
    "product_reviews.read",
    "product_reviews.update",
    "product_reviews.delete",
  ],
  seller: [
    "products.read",
    "orders.create",
    "orders.read",
    "receipts.create",
    "receipts.read",
    "product_reviews.create",
    "product_reviews.read",
    "product_reviews.update",
    "product_reviews.delete",
    "products.create",
    "products.update",
    "products.delete",
    "product_images.create",
    "product_images.read",
    "product_images.delete",
    "seller_payment_methods.create",
    "seller_payment_methods.read",
    "seller_payment_methods.update",
    "seller_payment_methods.delete",
    "orders.update",
    "templates.read",
  ],
  admin: [
    "products.read",
    "orders.create",
    "orders.read",
    "receipts.create",
    "receipts.read",
    "product_reviews.create",
    "product_reviews.read",
    "product_reviews.update",
    "product_reviews.delete",
    "products.create",
    "products.update",
    "products.delete",
    "product_images.create",
    "product_images.read",
    "product_images.delete",
    "seller_payment_methods.create",
    "seller_payment_methods.read",
    "seller_payment_methods.update",
    "seller_payment_methods.delete",
    "orders.update",
    "templates.read",
    "audit.read",
    "payment_method_types.create",
    "payment_method_types.read",
    "payment_method_types.update",
    "payment_method_types.delete",
    "payment_settings.read",
    "payment_settings.update",
    "templates.create",
    "templates.update",
    "templates.delete",
    "user_permissions.create",
    "user_permissions.read",
    "user_permissions.update",
    "user_permissions.delete",
    "events.create",
    "events.read",
    "events.update",
    "events.delete",
  ],
  none: [],
};

/** Maps permission keys to their depends_on parent (for warnings) */
export const PERMISSION_DEPENDENCIES: Record<string, string> = {
  "products.update": "products.create",
  "products.delete": "products.create",
  "product_images.create": "products.create",
  "product_images.delete": "products.create",
  "seller_payment_methods.create": "products.create",
  "seller_payment_methods.read": "products.create",
  "seller_payment_methods.update": "products.create",
  "seller_payment_methods.delete": "products.create",
  "orders.update": "products.create",
  "receipts.create": "orders.create",
  "product_reviews.create": "orders.create",
};

export const USER_PERMISSIONS_QUERY_KEY = "user-permissions";
export const USER_SEARCH_QUERY_KEY = "user-search";

/** Minimum characters required before triggering a user search */
export const MIN_USER_SEARCH_LENGTH = 3;

/** Reason stored in audit trail when permissions are changed via the admin UI */
export const ADMIN_UI_GRANT_REASON = "Admin UI";
